### ISSUE TITLE
Мало МОПа

### ISSUE THREAD

**Issue by Garetonchick** [scanhex12/relvec-db#1]
Проект имеет на данный момент критический недостаток. Это, конечно же, отсутствие каких либо технологий машинного обучения (ака МОП) в имплементации. В современном мире AI стало неотъемлемой частью любого успешного продукта, поэтому данное положение дел неприемлемо.

Что я предлагаю? Нужно встроить в БД поиск с помощью LLM модели. Сценарий использования следующий. Пользователь вводит обычный текстовый запрос, а модель преобразует его в SQL запрос, который в свою очередь попадает в БД.

**Comment by scanhex12** [comment]
добавил в экспы
